name: CI/CD with Kustomize and Kubernetes

on:
  push:
    branches:
      - dev
      - staging
      - main  # for production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'

      - name: Set up Kustomize
        run: |
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/latest/download/kustomize_linux_amd64
          chmod +x kustomize
          sudo mv kustomize /usr/local/bin/
          kustomize version


      - name: Set Kubeconfig
        env:
          KUBECONFIG_DATA: ${{ secrets.KUBECONFIG_DATA }}
        run: |
          mkdir -p $HOME/.kube
          echo "$KUBECONFIG_DATA" | base64 --decode > $HOME/.kube/config

      - name: Deploy to Kubernetes
        run: |
          if [[ "${GITHUB_REF##*/}" == "dev" ]]; then
            kubectl apply -k overlays/dev
          elif [[ "${GITHUB_REF##*/}" == "staging" ]]; then
            kubectl apply -k overlays/staging
          elif [[ "${GITHUB_REF##*/}" == "main" ]]; then
            kubectl apply -k overlays/prod
          fi

