name: CI/CD with Kustomize and Kubernetes

on:
  push:
    branches:
      - dev
      - staging
      - main  # production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'

      - name: Install Kustomize
        run: |
          curl -sLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/latest/download/kustomize_linux_amd64
          chmod +x kustomize
          sudo mv kustomize /usr/local/bin/
          kustomize version


      - name: Configure Kubeconfig
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        run: |
          mkdir -p $HOME/.kube
          echo "$KUBE_CONFIG_DATA" | base64 --decode > $HOME/.kube/config

      - name: Deploy to Kubernetes
        run: |
          BRANCH=${GITHUB_REF##*/}
          echo "Deploying overlay for branch: $BRANCH"
          case $BRANCH in
            dev)
              kubectl apply -k overlays/dev
              ;;
            staging)
              kubectl apply -k overlays/staging
              ;;
            main)
              kubectl apply -k overlays/prod
              ;;
            *)
              echo "No overlay found for branch: $BRANCH"
              ;;
          esac

