name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4

      - name: Update kubeconfig for EKS
          run: |
            aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name kustomize-capstone-cluster




      - name: Install Kustomize
        run: |
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/v5.7.1/kustomize_v5.7.1_linux_amd64.tar.gz
          tar -xzf kustomize_v5.7.1_linux_amd64.tar.gz
          sudo mv kustomize /usr/local/bin/
          kustomize version


      - name: Configure Kubeconfig
        env:
          KUBECONFIG_DATA: ${{ secrets.KUBECONFIG_DATA_PROD }}
        run: |
          mkdir -p ~/.kube
          echo "$KUBECONFIG_DATA" | base64 --decode > ~/.kube/config

      - name: Deploy to Production
        run: |
          kubectl apply -k overlays/prod

