name: CI/CD with Kustomize and Kubernetes

on:
  push:
    branches:
      - dev
      - staging
      - main  # production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'

      - name: Install Kustomize
        run: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
          sudo mv kustomize /usr/local/bin/
          kustomize version

      - name: Configure Kubeconfig
        env:
          KUBECONFIG_DATA: ${{ secrets.KUBECONFIG_DATA }}
        run: |
          mkdir -p $HOME/.kube
          echo "$KUBECONFIG_DATA" | base64 --decode > $HOME/.kube/config

      - name: Deploy using Kustomize
        run: |
          BRANCH_NAME="${GITHUB_REF##*/}"
          echo "Deploying for branch: $BRANCH_NAME"
          if [ "$BRANCH_NAME" = "dev" ]; then
            kubectl apply -k overlays/dev
          elif [ "$BRANCH_NAME" = "staging" ]; then
            kubectl apply -k overlays/staging
          elif [ "$BRANCH_NAME" = "main" ]; then
            kubectl apply -k overlays/prod
          else
            echo "No matching environment for branch: $BRANCH_NAME"
            exit 0
          fi

